spring.application.name=loggers

#logging.level.root=TRACE

#logging.level.com.example.loggers.controller=WARN
#logging.level.com.example.loggers.service=TRACE
#
#logging.file.name=logs/app_logs.txt
#
#logging.pattern.console=%d{yy-MMM-dd HH:mm:ss} [%thread] %-5level : %msg%n
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n